spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://onewayserver.online:7001/delivery_test
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
