spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.5.2.144:3306/delivery_test
    username: delivery-backend
    password: onewayservice
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
